FROM alpine:latest

# https://hub.docker.com/_/alpine/
# https://github.com/gliderlabs/docker-alpine/blob/master/versions/library-3.4/Dockerfile
MAINTAINER Jethro Tulling <jethro@jethro-tulling.com>
